/*******************************************************************************
  * @author     : wangming
  * @wechat     : DeepCoderMing
  * @qq         : 3201935299
  * @date       : 2025-05-01
  * @copyright  : For reference and learning only. Redistribution prohibited.
********************************************************************************/
#include "ti_msp_dl_config.h"
#include "drv_oled.h"
#include "ndrivers/LCD/lcd_init.h"
#include "hal_led.h"
#include "hal_key.h"
#include "hal_beep.h"
#include "hal_timer.h"
#include "hal_encode.h"
#include "hal_tb6612.h"
#include "hal_uart.h"
#include "hal_vofa.h"
#include "string.h"
#include "CPU.h"
#include "OS_System.h"
#include "App.h"
#include "hal_delay.h"
#include "hal_tb6612.h"
#include "mt_test.h"
#include "seekfree_uart.h"
#include "seekfree_assistant.h"
#include "move_filter.h"
#include "hal_at24c02.h"
#include "mt_flag.h"
#include "2024DS_Duty.h"
#include "zf_device_imu660ra.h"
#include "imu_filter.h"                  // Device header


int keynum = 0;
float test_eepro = 0.f;
unsigned char send_buff[] ={"hello,world!"};
uint8_t     debug_uart_buffer[64];           // UART data receive buffer
int main(void)
{
	SYSCFG_DL_init();// Chip power init, auto-generated by SysConfig
	hal_CPUInit();	// Timer 7 init, triggers OS scheduler
	OS_TaskInit();	// Task scheduler init
	oled_init();	// OLED display driver init
	LCD_Init();	// LCD init (replaces OLED)
	OLED_CLS();	// LCD full-screen clear to remove artifacts
	hal_KeyInit();	// Key state machine init
	ctrl_params_init();// Seek/speed loop PID controller params init
	hal_Encoder_Init();	// External interrupt encoder pulse acquisition
	//hal_uart1_Init();	// UART1 init PA10 PA11 for Zigbee
	//fifo_init(&debug_uart_fifo, FIFO_DATA_8BIT, debug_uart_buffer, 64);	// Zigbee UART FIFO
	TIMG0_Init();	// Timer interrupt, reads sensor values every 5ms
	TIMG6_Init(); // Timer interrupt, real-time clock 5ms
	//motor_self_test();	// Motor self-test disabled

	move_filter_init(&left_speed_cmps);	// Left wheel speed filter
	move_filter_init(&right_speed_cmps);	// Right wheel speed filter
	hal_uart1_Init();
	uart1_rx_register(vofa_uart_rx_callback);
	fifo_init(&debug_uart_fifo, FIFO_DATA_8BIT, debug_uart_buffer, 64);
	vofa_param_init();

	seekfree_assistant_init(); // Initialize seekfree assistant FIFO

	AppInit();
	Flag_Init();

	OS_CreatTask(OS_TASK1,hal_KeyProc,1,OS_RUN);  // Task 1: periodic key scan

	OS_CreatTask(OS_TASK2,AppProc,1,OS_RUN); // Task 2: multi-level menu

	OS_Start(); // Main loop starts; everything above is initialization	
}

